### ISSUE TITLE
Does the Zabbix server need to be external?

### ISSUE THREAD

**Issue by rkday-pro** [thomnico/juju-nfv-demo#15]
The current instructions feel a bit heavyweight (https://github.com/thomnico/juju-nfv-clearwater-restcomm/blob/master/README.md), since it talks about needing an external Zabbix server, manually configuring security groups, etc. Is it possible to not have this be external - to just set Zabbix up internally and automatically as another charm?

**Comment by thomnico** [comment]
Sure it is possible ... we will do both eventually .

Having it external allow to show how to "create your orchestration on top"
and use the API which is very often asked ..

On Thu, Jul 23, 2015 at 5:27 PM, Rob Day notifications@github.com wrote:

> The current instructions feel a bit heavyweight (
> https://github.com/thomnico/juju-nfv-clearwater-restcomm/blob/master/README.md),
> since it talks about needing an external Zabbix server, manually
> configuring security groups, etc. Is it possible to not have this be
> external - to just set Zabbix up internally and automatically as another
> charm?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thomnico/juju-nfv-clearwater-restcomm/issues/15.

## 

Best Regards,
       Nicolas Thomas
http://insights.ubuntu.com/?p=889
EMEA Solution Architect              Canonical
GPG FPR: D592 4185 F099 9031 6590 6292 492F C740 F03A 7EB9
