### ISSUE TITLE
Deployment does not work on AWS due to  dns - install hook failure

### ISSUE THREAD

**Issue by tyloch** [thomnico/juju-nfv-demo#18]
bundle deployment on AWS using `01-deploy.sh` failed as DNS install hook failing 

see log below:
     `juju debug-log --replay | grep unit-dns-0` 

unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise Release.gpg
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates Release.gpg
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise Release
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates Release
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main Sources
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe Sources
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main Sources
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe Sources
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security Release.gpg
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security Release
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools Release.gpg
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main Sources
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe Sources
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools Release
unit-dns-0[3705]: 2015-09-20 00:55:00 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Hit http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools/main amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Hit http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools/main i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Ign http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools/main TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:01 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:02 INFO unit.dns/0.install logger.go:40 Ign http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools/main Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:23 INFO unit.dns/0.install logger.go:40 Reading package lists...
unit-dns-0[3705]: 2015-09-20 00:55:23 INFO unit.dns/0.juju-log server.go:254 Installing ['python-pip'] with options: ['--option=Dpkg::Options::=--force-confold']
unit-dns-0[3705]: 2015-09-20 00:55:24 INFO unit.dns/0.install logger.go:40 Reading package lists...
unit-dns-0[3705]: 2015-09-20 00:55:24 INFO unit.dns/0.install logger.go:40 Building dependency tree...
unit-dns-0[3705]: 2015-09-20 00:55:24 INFO unit.dns/0.install logger.go:40 Reading state information...
unit-dns-0[3705]: 2015-09-20 00:55:25 INFO unit.dns/0.install logger.go:40 The following extra packages will be installed:
unit-dns-0[3705]: 2015-09-20 00:55:25 INFO unit.dns/0.install logger.go:40   python-setuptools
unit-dns-0[3705]: 2015-09-20 00:55:25 INFO unit.dns/0.install logger.go:40 The following NEW packages will be installed:
unit-dns-0[3705]: 2015-09-20 00:55:25 INFO unit.dns/0.install logger.go:40   python-pip python-setuptools
unit-dns-0[3705]: 2015-09-20 00:55:25 INFO unit.dns/0.install logger.go:40 0 upgraded, 2 newly installed, 0 to remove and 8 not upgraded.
unit-dns-0[3705]: 2015-09-20 00:55:25 INFO unit.dns/0.install logger.go:40 Need to get 536 kB of archives.
unit-dns-0[3705]: 2015-09-20 00:55:25 INFO unit.dns/0.install logger.go:40 After this operation, 1467 kB of additional disk space will be used.
unit-dns-0[3705]: 2015-09-20 00:55:25 INFO unit.dns/0.install logger.go:40 Get:1 http://us-west-1.ec2.archive.ubuntu.com/ubuntu/ precise/main python-setuptools all 0.6.24-1ubuntu1 [441 kB]
unit-dns-0[3705]: 2015-09-20 00:55:25 INFO unit.dns/0.install logger.go:40 Get:2 http://us-west-1.ec2.archive.ubuntu.com/ubuntu/ precise/universe python-pip all 1.0-1build1 [95.1 kB]
unit-dns-0[3705]: 2015-09-20 00:55:26 INFO unit.dns/0.install logger.go:40 Fetched 536 kB in 0s (9100 kB/s)
unit-dns-0[3705]: 2015-09-20 00:55:26 INFO unit.dns/0.install logger.go:40 Selecting previously unselected package python-setuptools.
unit-dns-0[3705]: 2015-09-20 00:55:26 INFO unit.dns/0.install logger.go:40 (Reading database ... 47757 files and directories currently installed.)
unit-dns-0[3705]: 2015-09-20 00:55:26 INFO unit.dns/0.install logger.go:40 Unpacking python-setuptools (from .../python-setuptools_0.6.24-1ubuntu1_all.deb) ...
unit-dns-0[3705]: 2015-09-20 00:55:26 INFO unit.dns/0.install logger.go:40 Selecting previously unselected package python-pip.
unit-dns-0[3705]: 2015-09-20 00:55:26 INFO unit.dns/0.install logger.go:40 Unpacking python-pip (from .../python-pip_1.0-1build1_all.deb) ...
unit-dns-0[3705]: 2015-09-20 00:55:26 INFO unit.dns/0.install logger.go:40 Processing triggers for man-db ...
unit-dns-0[3705]: 2015-09-20 00:55:27 INFO unit.dns/0.install logger.go:40 Setting up python-setuptools (0.6.24-1ubuntu1) ...
unit-dns-0[3705]: 2015-09-20 00:55:28 INFO unit.dns/0.install logger.go:40 Setting up python-pip (1.0-1build1) ...
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Downloading/unpacking nose (from -r requirements.txt (line 1))
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40   Running setup.py egg_info for package nose
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40  
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40     no previously-included directories found matching 'doc/.build'
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Downloading/unpacking flake8 (from -r requirements.txt (line 2))
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40   Running setup.py egg_info for package flake8
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40  
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Downloading/unpacking mock (from -r requirements.txt (line 3))
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40   Running setup.py egg_info for package mock
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40     mock requires setuptools>=17.1. Aborting installation
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40     Complete output from command python setup.py egg_info:
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40     mock requires setuptools>=17.1. Aborting installation
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 ----------------------------------------
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Command python setup.py egg_info failed with error code 1
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Storing complete log in /root/.pip/pip.log
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise Release.gpg
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates Release.gpg
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise Release
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates Release
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main Sources
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe Sources
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main Sources
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe Sources
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security Release.gpg
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/main Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise/universe Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/main Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://us-west-1.ec2.archive.ubuntu.com precise-updates/universe Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security Release
unit-dns-0[3705]: 2015-09-20 00:55:34 INFO unit.dns/0.install logger.go:40 Hit http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools Release.gpg
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main Sources
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe Sources
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools Release
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools/main amd64 Packages
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools/main i386 Packages
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Ign http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools/main TranslationIndex
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/main Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:35 INFO unit.dns/0.install logger.go:40 Hit http://security.ubuntu.com precise-security/universe Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:36 INFO unit.dns/0.install logger.go:40 Ign http://ubuntu-cloud.archive.canonical.com precise-updates/cloud-tools/main Translation-en
unit-dns-0[3705]: 2015-09-20 00:55:57 INFO unit.dns/0.install logger.go:40 Reading package lists...
unit-dns-0[3705]: 2015-09-20 00:55:57 INFO unit.dns/0.juju-log server.go:254 Installing ['bind9', 'dnsutils'] with options: ['--option=Dpkg::Options::=--force-confold']
unit-dns-0[3705]: 2015-09-20 00:55:57 INFO unit.dns/0.install logger.go:40 Reading package lists...
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 Building dependency tree...
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 Reading state information...
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 dnsutils is already the newest version.
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 The following extra packages will be installed:
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40   bind9utils libcap2
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 Suggested packages:
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40   bind9-doc
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 The following NEW packages will be installed:
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40   bind9 bind9utils libcap2
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 0 upgraded, 3 newly installed, 0 to remove and 8 not upgraded.
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 Need to get 459 kB of archives.
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 After this operation, 1328 kB of additional disk space will be used.
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 Get:1 http://us-west-1.ec2.archive.ubuntu.com/ubuntu/ precise/main libcap2 amd64 1:2.22-1ubuntu3 [12.0 kB]
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 Get:2 http://us-west-1.ec2.archive.ubuntu.com/ubuntu/ precise-updates/main bind9utils amd64 1:9.8.1.dfsg.P1-4ubuntu0.13 [105 kB]
unit-dns-0[3705]: 2015-09-20 00:55:58 INFO unit.dns/0.install logger.go:40 Get:3 http://us-west-1.ec2.archive.ubuntu.com/ubuntu/ precise-updates/main bind9 amd64 1:9.8.1.dfsg.P1-4ubuntu0.13 [343 kB]
unit-dns-0[3705]: 2015-09-20 00:55:59 INFO unit.dns/0.install logger.go:40 Preconfiguring packages ...
unit-dns-0[3705]: 2015-09-20 00:55:59 INFO unit.dns/0.install logger.go:40 Fetched 459 kB in 0s (10.3 MB/s)
unit-dns-0[3705]: 2015-09-20 00:55:59 INFO unit.dns/0.install logger.go:40 Selecting previously unselected package libcap2.
unit-dns-0[3705]: 2015-09-20 00:55:59 INFO unit.dns/0.install logger.go:40 (Reading database ... 47972 files and directories currently installed.)
unit-dns-0[3705]: 2015-09-20 00:55:59 INFO unit.dns/0.install logger.go:40 Unpacking libcap2 (from .../libcap2_1%3a2.22-1ubuntu3_amd64.deb) ...
unit-dns-0[3705]: 2015-09-20 00:55:59 INFO unit.dns/0.install logger.go:40 Selecting previously unselected package bind9utils.
unit-dns-0[3705]: 2015-09-20 00:55:59 INFO unit.dns/0.install logger.go:40 Unpacking bind9utils (from .../bind9utils_1%3a9.8.1.dfsg.P1-4ubuntu0.13_amd64.deb) ...
unit-dns-0[3705]: 2015-09-20 00:56:00 INFO unit.dns/0.install logger.go:40 Selecting previously unselected package bind9.
unit-dns-0[3705]: 2015-09-20 00:56:00 INFO unit.dns/0.install logger.go:40 Unpacking bind9 (from .../bind9_1%3a9.8.1.dfsg.P1-4ubuntu0.13_amd64.deb) ...
unit-dns-0[3705]: 2015-09-20 00:56:00 INFO unit.dns/0.install logger.go:40 Processing triggers for man-db ...
unit-dns-0[3705]: 2015-09-20 00:56:02 INFO unit.dns/0.install logger.go:40 Processing triggers for ureadahead ...
unit-dns-0[3705]: 2015-09-20 00:56:02 INFO unit.dns/0.install logger.go:40 Processing triggers for ufw ...
unit-dns-0[3705]: 2015-09-20 00:56:02 INFO unit.dns/0.install logger.go:40 Setting up libcap2 (1:2.22-1ubuntu3) ...
unit-dns-0[3705]: 2015-09-20 00:56:02 INFO unit.dns/0.install logger.go:40 Setting up bind9utils (1:9.8.1.dfsg.P1-4ubuntu0.13) ...
unit-dns-0[3705]: 2015-09-20 00:56:02 INFO unit.dns/0.install logger.go:40 Setting up bind9 (1:9.8.1.dfsg.P1-4ubuntu0.13) ...
unit-dns-0[3705]: 2015-09-20 00:56:04 INFO unit.dns/0.install logger.go:40 Adding group `bind' (GID 112) ...
unit-dns-0[3705]: 2015-09-20 00:56:04 INFO unit.dns/0.install logger.go:40 Done.
unit-dns-0[3705]: 2015-09-20 00:56:04 INFO unit.dns/0.install logger.go:40 Adding system user`bind' (UID 106) ...
unit-dns-0[3705]: 2015-09-20 00:56:04 INFO unit.dns/0.install logger.go:40 Adding new user `bind' (UID 106) with group`bind' ...
unit-dns-0[3705]: 2015-09-20 00:56:04 INFO unit.dns/0.install logger.go:40 Not creating home directory `/var/cache/bind'.
unit-dns-0[3705]: 2015-09-20 00:56:04 INFO unit.dns/0.install logger.go:40 wrote key file "/etc/bind/rndc.key"
unit-dns-0[3705]: 2015-09-20 00:56:04 INFO unit.dns/0.install logger.go:40 #
unit-dns-0[3705]: 2015-09-20 00:56:05 INFO unit.dns/0.install logger.go:40  \* Starting domain name service... bind9
unit-dns-0[3705]: 2015-09-20 00:56:05 INFO unit.dns/0.install logger.go:40    ...done.
unit-dns-0[3705]: 2015-09-20 00:56:06 INFO unit.dns/0.install logger.go:40 Processing triggers for libc-bin ...
unit-dns-0[3705]: 2015-09-20 00:56:06 INFO unit.dns/0.install logger.go:40 ldconfig deferred processing now taking place
unit-dns-0[3705]: 2015-09-20 00:56:09 INFO unit.dns/0.install logger.go:40 Traceback (most recent call last):
unit-dns-0[3705]: 2015-09-20 00:56:09 INFO unit.dns/0.install logger.go:40   File "/var/lib/juju/agents/unit-dns-0/charm/hooks/install", line 75, in <module>
unit-dns-0[3705]: 2015-09-20 00:56:09 INFO unit.dns/0.install logger.go:40     i.install_provider()
unit-dns-0[3705]: 2015-09-20 00:56:09 INFO unit.dns/0.install logger.go:40   File "/var/lib/juju/agents/unit-dns-0/charm/hooks/install", line 56, in install_provider
unit-dns-0[3705]: 2015-09-20 00:56:09 INFO unit.dns/0.install logger.go:40     import DNS
unit-dns-0[3705]: 2015-09-20 00:56:09 INFO unit.dns/0.install logger.go:40 ImportError: No module named DNS
unit-dns-0[3705]: 2015-09-20 00:56:09 ERROR juju.worker.uniter.operation runhook.go:103 hook "install" failed: exit status 1

**Comment by tyloch** [comment]
still does not work: 

2015-09-23 19:38:09 The following units had errors:
   unit: dns/0: machine: 37 agent-state: error details: hook failed: "programmable-multiple-relation-changed"
2015-09-23 19:38:09 Deployment stopped. run time: 849.62

**Comment by thomnico** [comment]
Fixed in
