### ISSUE TITLE
Scalability test  

### ISSUE THREAD

**Issue by tyloch** [thomnico/juju-nfv-demo#19]
We could implement scalability test case using  clearwater sipp usage to stress using a real workload engine.

**Comment by rkday-pro** [comment]
We have https://github.com/Metaswitch/clearwater-juju/tree/dnsaas/charms/precise/clearwater-sipp - a charm that runs SIPp against Clearwater. I'll look at incorporating this.

**Comment by tyloch** [comment]
ok, please add this to this environment and document how to use it. 
Please remember that for AWS we will have approx. 20 nodes (to be shared with other services like Restcomm, OpenCell etc. ) but this should be sufficient to demo scalability
