### ISSUE TITLE
Latest versions of clearwater-juju and DNSCharm

### ISSUE THREAD

**Issue by rkday-pro** [thomnico/juju-nfv-demo#23]
We've made several fixes to clearwater-juju (https://github.com/Metaswitch/clearwater-juju/), particularly around stress configuration (e.g. number of users, overload control) and allowing configuration of a CDF for billing.

We've also submitted https://github.com/chuckbutler/DNS-Charm/pull/28, which allows DNS records to be added correctly on scale-up.

Can you make sure that https://github.com/thomnico/juju-nfv-clearwater-restcomm/blob/master/00-prepare.sh checks out Git branches with those changes in?

**Comment by thomnico** [comment]
I did recently .. please rm clearwater-juju and retry .. let me know if it is the right one.
