### ISSUE TITLE
clearwater-homer/1    -  hook failed: "install"

### ISSUE THREAD

**Issue by tyloch** [thomnico/juju-nfv-demo#27]
For EC2 deployment I am getting install hook failure for clearwater-homer/1

machine-0: 2016-03-18 07:01:10 WARNING juju.apiserver.client status.go:677 error fetching public address: public no address
unit-clearwater-homer-1[1046]: 2016-03-18 07:01:34 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1

**Comment by tyloch** [comment]
failing due to EC2 limit? Investigating.

**Comment by thomnico** [comment]
Nope the current code is not functionning and not maintained

On Fri, Mar 18, 2016 at 8:20 AM, Artur Tyloch notifications@github.com
wrote:

> failing due to EC2 limit? Investigating.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/thomnico/juju-nfv-clearwater-restcomm/issues/27#issuecomment-198236903

## 

Best Regards,
       Nicolas Thomas
http://insights.ubuntu.com/?p=889
EMEA Solution Architect              Canonical
GPG FPR: D592 4185 F099 9031 6590 6292 492F C740 F03A 7EB9
