### ISSUE TITLE
rename for more demos

### ISSUE THREAD

**Issue by tyloch** [thomnico/juju-nfv-demo#4]
As we will have multiple demos with various architectures - it would be good  to rename juju-nfv-demo to e.g. juju-nfv-demo-1 or juju-nfv-demo-IMS-SDPscale (to keep name space open).

**Comment by thomnico** [comment]
I was thinking of exactly that.. Let's use our partners name for better
awareness of their users/developers

**Comment by tyloch** [comment]
yes.
On the other hand I though maybe it would be good idea to have separate project for every demo. 
i.e. you will have different people working on demo with unique notifications and bug tracking. 
On top we could have one project to aggregate all those "subprojects". 
Drawback - less visibility on other projects and fixes.

**Comment by thomnico** [comment]
All good things will end up in the charms hence store...

I prefer to get started and adapt along the way than creating something
rigid from start

**Comment by tyloch** [comment]
true
